# Generated by Django 2.2 on 2019-05-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20190502_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
