# Generated by Django 2.2 on 2019-05-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20190502_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='0000', max_length=50),
            preserve_default=False,
        ),
    ]
